### ISSUE TITLE
Remove styles of all the text

### ISSUE THREAD

**Issue by BrodaNoel** [andrey-semin/draft-js-clear-formatting#1]
Hello!
Guys, I see that this plugin works perfectly for removing the styles of a selected text.
Is there a way to remove the styles of all the text, with no selecting it?

**Comment by andrey-semin** [comment]
Hi @BrodaNoel! You can mark whole editor content as selected before calling `clearFormatting` function.

**Comment by andrey-semin** [comment]
@BrodaNoel is this issue still actual?
